name: underdogdesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00739c'
    - '#5ba5c0'
    - '#c9e1eb'
    - '#fe7d05'
    - '#884c41'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
